version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  reek:
    enabled: true
    checks:
      Attribute:
        enabled: false
  rubocop:
    enabled: true